[package]
name = "hpc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cudarc = "0.10.0"
libc = "0.2"

[build-dependencies]
bindgen_cuda = "0.1.5"