[package]
name = "hpc-rs"
version = "0.1.0"
edition = "2021"

[dependencies]


[build-dependencies]
bindgen_cuda = "0.1.5"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "array_add"
harness = false